from measurable import Measurable

def main():
    number1 = float(input("Enter number1: "))
    number2 = float(input("Enter number2: "))
    number3 = float(input("Enter number3: "))
    number4 = float(input("Enter numebr4: "))

    first = Measurable(number1, number2)
    second = Measurable(number3, number4)

    print("-------------------- first object --------------------")
    print("1)", first.getNumerator())
    print("2)", first.getDenominator())
    print("3)", float(first))
    print("4)", first.__neg__())
    print("5)", first.__pos__())
    print("6)", first + second)
    print("7)", first.__iadd__(second))
    print("8)", first - second)
    print("9)", first.__isub__(second))
    print("10)", first == second)
    print("11)", first != second)
    print("12)", first < second)
    print("13)", first <= second)
    print("14)", first > second)
    print("15)", first >= second)
    print("16)", first * second)
    print("17)", first / second)
    print("18)", first // second)
    print("19)", repr(first))
    print("20)", first)

    print("-------------------- second object --------------------")
    print("1)", second.getNumerator())
    print("2)", second.getDenominator())
    print("3)", float(second))
    print("4)", second.__neg__())
    print("5)", second.__pos__())
    print("6)", second + first)
    print("7)", second.__iadd__(first))
    print("8)", second - first)
    print("9)", first.__isub__(second))
    print("10)", second == first)
    print("11)", second != first)
    print("12)", second < first)
    print("13)", second <= first)
    print("14)", second > first)
    print("15)", second >= first)
    print("16)", second * first)
    print("17)", second / first)
    print("18)", second // first)
    print("19)", repr(second))
    print("20)", second)


if __name__ == "__main__":
    main()